# Generated by Django 4.0 on 2021-12-30 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(db_index=True)),
                ('verified', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True)),
                ('username', models.TextField(blank=True, db_index=True, default=None, null=True, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email_address', models.TextField(blank=True, db_index=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('twitter', models.TextField(blank=True, default=None, null=True)),
                ('insta', models.TextField(blank=True, default=None, null=True)),
                ('website', models.TextField(blank=True, default=None, null=True)),
                ('profile_image', models.TextField(blank=True, default=None, null=True)),
                ('profile_banner', models.TextField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_sold', models.BooleanField(default=True)),
                ('bid_activity', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
        ),
    ]
