# Generated by Django 4.0 on 2022-01-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dst_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_dst_profile', to='userprofile.profile')),
                ('src_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_src_profile', to='userprofile.profile')),
            ],
        ),
    ]
