# Generated by Django 4.0 on 2022-01-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profilefollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.TextField(db_index=True)),
                ('remote_ip', models.TextField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
