# Generated by Django 4.0 on 2022-02-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_securityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='remote_ip',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
