# Generated by Django 4.0 on 2022-02-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_securityevent_remote_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='meta',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Email changed')]),
        ),
    ]
