# Generated by Django 4.0 on 2022-02-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_securityevent_meta_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_banner_hash',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_hash',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
