# Generated by Django 4.0 on 2022-02-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userprofile', '0008_usernotification_delete_usernotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='profile',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
