# Generated by Django 4.0 on 2021-12-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSCERC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ETHERC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='POLYERC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='XDAIERC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('decimals', models.IntegerField()),
            ],
        ),
    ]
