# Generated by Django 4.0 on 2021-12-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bscerc20',
            name='ident',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etherc20',
            name='ident',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='polyerc20',
            name='ident',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='xdaierc20',
            name='ident',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
