import { Link } from '@reach/router';
import { useSelector } from "react-redux"


const LoginButton = () => {

    const profile = useSelector((state) => state.profile.profile);
    //const [loadingBusy, setLoadingBusy] = useState(false);

    const wallet_display = (profile) => {

        // Placeholder until we do multi-wallet integration and to shut the linter up
        // setLoadingBusy(false);

        if(profile === null) {
            return null;
        }

        var wallet_addr = profile.address;

        if(wallet_addr === undefined || wallet_addr === null) {
            return null;
        }
        else {
            return '0x' + wallet_addr.slice(2, 5) + '..'  + wallet_addr.slice(wallet_addr.length - 3)
        }
    }

    return (
        <div className='mainside'>
            <Link to="/wallet" className="btn-main">
            
            
            {false && 
                <>
                    {/* This is generated by loader.io, look at all those divs https://www.youtube.com/watch?v=NsLKQTh-Bqo */}
                    <div class="loadingio-spinner-spinner" >
                        <div class="ldio-spinner">
                            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
                        </div>
                    </div>            
                </>
            }

            {!false && 
                <>
                    {wallet_display(profile) || 'Connect Wallet'}
                </>
            }

            </Link>
        </div>
    )
}

export default LoginButton;
