# Generated by Django 4.0 on 2022-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.IntegerField(choices=[(0, '24 Hour'), (1, '7 Days'), (2, '30 Days'), (3, 'All time')])),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('stats', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
