# Generated by Django 4.0 on 2022-01-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='post_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
