# Generated by Django 4.0 on 2022-01-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspost_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='blog_content_preview',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
