# Generated by Django 4.0 on 2022-02-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_nftvoucher_min_price_nftvoucher_token_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftitemactivity',
            name='activity_type',
            field=models.IntegerField(choices=[(1, 'Mint'), (2, 'Purchase'), (4, 'Offer'), (5, 'Favourite'), (6, 'Follow')], db_index=True),
        ),
    ]
