# Generated by Django 4.0 on 2022-02-07 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_alter_nftitemactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='pending_itemactivity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_nftitemactivity', to='nft.nftitemactivity'),
        ),
        migrations.AddField(
            model_name='nftitemactivity',
            name='wallet_from',
            field=models.TextField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nftitemactivity',
            name='wallet_to',
            field=models.TextField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nftitemactivity',
            name='activity_type',
            field=models.IntegerField(choices=[(1, 'Mint'), (2, 'Purchase'), (3, 'Transfer'), (4, 'Offer'), (5, 'Favourite'), (6, 'Follow')], db_index=True),
        ),
    ]
